"""Add last_voted_mode column to Class

Revision ID: ce83bdafd9b9
Revises: 
Create Date: 2023-05-23 12:16:59.398818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce83bdafd9b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class', sa.Column('last_voted_mode', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('class', 'last_voted_mode')
    # ### end Alembic commands ###
