"""Add last_voted_mode column to Class

Revision ID: e99785d5cf1e
Revises: ce83bdafd9b9
Create Date: 2023-05-23 12:19:03.991204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e99785d5cf1e'
down_revision = 'ce83bdafd9b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votation', sa.Column('last_voted_mode', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('votation', 'last_voted_mode')
    # ### end Alembic commands ###
